  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "ErrantAbun"
  weight = 300
  identifier = "errantabun"
  url = "/errantabun/"

  [[main]]
  name = "Thesis"
  weight = 400
  identifier = "thesis"
  url = "/thesis/"
  
  [[main]]
  name = "AddressParse"
  weight = 500
  identifier = "addressparse"
  url = "/addressparse/"
  
  [[main]]
  name = "CV"
  weight = 600
  identifier = "CV"
  url = "/cv/"

  [[main]]
  name = "About"
  weight = 700
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Contact"
  weight = 800
  identifier = "contact"
  url = "/contact/"