
title = "the datum"
author = "the datum"
copyright = "Jan 2022"
description = "A website for data science and statistics enthusiasts. Welcome to my portfolio/blog."
profilePicture = "images/thedatum.svg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Google Analytics
googleAnalytics = "UA-197726431-1"
# Form Spree Contact Form
contactFormAction = "https://formspree.io/f/xwkalavg"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2006-01-02"
indexDateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = true
use = "katex"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/jeonghoon-lee"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/JohntheLee?tab=repositories"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:jeonghoon.lee@mail.utoronto.ca"