---
title: ErrantAbun Package
description: Jeonghoon Lee's ErrantAbun R Package
author: Jeonghoon Lee
date: '2021-06-11'
output:
  blogdown::html_page:
    highlight: tango
slug: []
categories: []
tags: []
DisableComments: Yes
---

Title: Calculation Of An Abundance Matrix Using A Randomized Distribution

Version: 1.0.2

Author: Jeonghoon Lee

This package contains the "errantabun" function which produces an errant species abundance matrix. This errant species abundance matrix is calculated from an original species abundance matrix and a randomized, statistical distribution. Currently, the available statistical distributions are Poisson and binomial. This function utilizes the "rpois" and the "rbinom" functions to create an abundance distribution for each species. The lambda for the Poisson distribution is the original abundance (vector) for each species. The size for the binomial distribution is the original abundance (vector) for each species.

This package also contains a sample abundance matrix collected from the Koffler Scientific Reserve at Joker's Hill (University of Toronto). Fourteen blocks serve as disparate communities of grassland plant species. Each block contains an array of different-sized plots: eight $0.5m^2$, eight $1m^2$, and four $2m^2$ plots. Each column of this abundance matrix represents a grassland plant species. Each row represents one of four $2m^2$ plots from all 14 blocks.

Imports: dplyr, magrittr, stats

License: MIT + file LICENSE

To-do List:

- add more statistical distributions
- incorporate native pipe
- finalize readme file